name: resto_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider:
  http:
  google_fonts:
  sqflite:
  shared_preferences:
  flutter_local_notifications:
  flutter_timezone:
  timezone:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true